apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booktracker-covers-pvc
  namespace: booktracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
