apiVersion: v1
kind: Service
metadata:
  name: booktracker
  namespace: booktracker
  labels:
    app: booktracker
spec:
  type: NodePort
  selector:
    app: booktracker
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30090
